// This is an autogenerated file from Firebase Studio.
"use client";

import Image from 'next/image';
import { Star, MessageSquareQuote } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import type { Testimonial } from '@/lib/data';
// Removed testimonialSummarizer and related imports as the feature is being removed.

interface TestimonialItemProps {
  testimonial: Testimonial;
}

export function TestimonialItem({ testimonial }: TestimonialItemProps) {
  // Removed state and effects related to AI summarization.

  return (
    <Card className="h-full flex flex-col glassmorphic overflow-hidden shadow-lg hover:shadow-primary/30 transition-shadow duration-300">
      <CardHeader className="flex flex-row items-start gap-4 p-4 md:p-6">
        {testimonial.avatarUrl && (
          <Image
            src={testimonial.avatarUrl}
            alt={testimonial.name}
            width={60}
            height={60}
            className="rounded-full border-2 border-primary/50"
            data-ai-hint={testimonial.dataAiHint || "person"}
          />
        )}
        <div className="flex-1">
          <CardTitle className="text-lg font-semibold text-foreground">{testimonial.name}</CardTitle>
          <p className="text-sm text-foreground/70">{testimonial.company}</p>
          <div className="flex items-center mt-1">
            {[...Array(5)].map((_, i) => (
              <Star
                key={i}
                className={`h-4 w-4 ${i < testimonial.rating ? 'text-yellow-400 fill-yellow-400' : 'text-muted-foreground'}`}
              />
            ))}
          </div>
        </div>
      </CardHeader>
      <CardContent className="p-4 md:p-6 pt-0 flex-grow">
        <blockquote className="italic text-foreground/80 border-l-4 border-primary/50 pl-4 py-2 mb-4">
          <MessageSquareQuote className="inline-block h-5 w-5 mr-2 text-primary/70 transform -scale-x-100" />
          {testimonial.quote}
        </blockquote>
        {/* AI Summary section has been removed */}
      </CardContent>
      {/* CardFooter is removed as it's no longer needed without the summarize button */}
    </Card>
  );
}
